apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-config-operator
  namespace: cattle-system
spec:
  replicas: 1
  selector:
    matchLabels:
      ke.cattle.io/operator: gke
  template:
    metadata:
      labels:
        ke.cattle.io/operator: gke
    spec:
      serviceAccountName: gke-operator
      containers:
      - name: gke-operator
        image: {{ template "system_default_registry" . }}{{ .Values.gkeOperator.image.repository }}:{{ .Values.gkeOperator.image.tag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: HTTP_PROXY
          value: {{ .Values.httpProxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.httpsProxy }}
        - name: NO_PROXY
          value: {{ .Values.noProxy }}
{{- if .Values.additionalTrustedCAs }}
        volumeMounts:
        - mountPath: /etc/ssl/certs/ca-additional.pem
          name: tls-ca-additional-volume
          subPath: ca-additional.pem
          readOnly: true
      volumes:
      - name: tls-ca-additional-volume
        secret:
          defaultMode: 0400
          secretName: tls-ca-additional
{{- end }}
